### ISSUE TITLE
Please add a license and a screen shot and consider renaming

### ISSUE THREAD

**Issue by unixorn** [alkuzad/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The name `zsh-theme` is very generic. Please consider renaming it to something descriptive, or even just name it after your github username or the plugin file in the repo

Thanks!

**Comment by alkuzad** [comment]
Hi @unixorn , thanks but it's not done yet, I am changing it constantly. Won't be usable by people I believe.

The screenshot also does not make sense because the theme is just a set of prompts on top of terminal emulator settings. I am  using light background for example and this is tuned for it, to get the same experience you would need the same Windows Terminal settings like me (using Espresso Soda)

**Comment by unixorn** [comment]
Ok, fair enough. If you get it to a point where it makes sense to share, please reopen this issue or file a PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).
